version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - GIPHY_API_KEY=${GIPHY_API_KEY}
      - PORT=5050
    ports:
      - "5050:5050"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5050/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      - REACT_APP_API_URL=http://backend:5050/api
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
